setlocal autoindent
setlocal expandtab
setlocal shiftround
setlocal shiftwidth=4
setlocal smartindent
setlocal softtabstop=4
setlocal tabstop=4
"setlocal textwidth=79
setlocal wrap
setlocal foldmethod=indent
